version: '3.4'

services:
  techchallenge-lanchonetetotem:
    image: ${DOCKER_REGISTRY-}techchallengelanchonetetotem
    build:
      context: .
      dockerfile: TechChallenge-LanchoneteTotem/Dockerfile
    ports:
      - "7003:80"
      - "7004:443"
    networks:
      - prod-network
    environment:
        MongoDbSettings_ConnectionString: 'mongodb://admin:abc123!@mongodbLanchonete'
    depends_on:
        - mongodb

  pagamentopedidonotificationconsumer:
     image: ${DOCKER_REGISTRY-}pagamentopedidonotificationconsumer
     build:
         context: .
         dockerfile: PagamentoPedidoNotificationConsumer/Dockerfile
     ports:
         - "7005:80"
         - "7006:443"
     networks:
         - prod-network
     environment:
         MongoDbSettings_ConnectionString: 'mongodb://admin:abc123!@mongodbLanchonete'
         LocalStack__Config__LocalStackHost: 'localstack'
     depends_on:
         - mongodb
         - localstack

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=sqs,s3
    # volumes:
    #   - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
    #   - "/var/run/docker.sock:/var/run/docker.sock"

  mongodb:
     image: mongo:latest
     networks:
       - prod-network
     container_name: mongodbLanchonete
     command: mongod --port 27017 --bind_ip 0.0.0.0
     environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'abc123!'

networks:
  prod-network:
    driver: bridge