---
apiVersion: v1
kind: Service
metadata:
  name: private-lb-totem-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: techchallenge-lanchonetetotem
  ports:
    - protocol: TCP
      port: 80
      targetPort: web-totem-api


---
apiVersion: v1
kind: Service
metadata:
  name: private-lb-consumer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: pagamentopedidonotificationconsumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: web-consumer



---
apiVersion: v1
kind: Service
metadata:
  name: private-lb-notifier
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: web-notifier