---
apiVersion: v1
kind: Service
metadata:
  name: public-lb-totem-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: techchallenge-lanchonetetotem
  ports:
    - protocol: TCP
      port: 80


---
apiVersion: v1
kind: Service
metadata:
  name: public-lb-consumer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: pagamentopedidonotificationconsumer
  ports:
    - protocol: TCP
      port: 80


---
apiVersion: v1
kind: Service
metadata:
  name: public-lb-notifier
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: notifier
  ports:
    - protocol: TCP
      port: 80

